### ISSUE TITLE
Spamming Cure after waking from zzz

### ISSUE THREAD

**Issue by Hallabaloo4** [lorand-ffxi/HealBot#18]
Everything runs fine until either i or the bot manages to get put to sleep.
As soon as that happens, the bot casts/queues cure to wake Me/Itself up and then won't stop spamming Cure on Me/Itself until i reset the client entirely

**Comment by lorand-ffxi** [comment]
I don't remember implementing cure to wakeup from sleep...  In fact I don't see any references to it in the code.  Sorry but I don't know why that's happening / would happen.  I have cancelled my FFXI sub due to not having enough time lately, so will not be able to help with this for the foreseeable future.

**Comment by lorand-ffxi** [comment]
There was no sleep wakeup implemented.  I am working in a separate branch to implement a wake up from sleep feature, but don't know when I will have the time to finish it.  I am closing this, as cure to wake from sleep was not implemented when this bug was filed.
